### ISSUE TITLE
Shinyapp hardcoded part

### ISSUE THREAD

**Issue by ritututeja** [HuffordLab/GenomeQC#1]
I would like to integrate the Shiny app in my pipeline. I downloaded the code from your GitHub repo but I could not make it work on my system. I noticed some of the paths are hardcoded in the app. Could you please help.

Thanks,
Reetu

**Comment by aseetharam** [comment]
Thanks for trying out GenomeQC! We do have a docker build that you can pull and run it locally without installing anything. Please try that out first. Unfortunately, at this point we don't think we could support local installation as it involves numerous dependencies. Please do let us know if you run in to any problem with docker! Thanks!
