### ISSUE TITLE
contamination.py requires blobtools being installed

### ISSUE THREAD

**Issue by ipetrushin** [HuffordLab/GenomeQC#2]
Dear GenomeQC team!

Following lines belongs to BlobTools
```
import lib.BtLog as BtLog
import lib.BtIO as BtIO
```
To run the script I had to manually add "lib" from BlobTools folder to scripts folder.

**Comment by nm100** [comment]
Thanks for trying GenomeQC! If you are using the docker file for building the image then you don't need to install the BlobTools or any other dependencies. The docker directory contain these two blobtool libraries (BtIO.py and BtLog.py) needed to run the contamination script. Also please use the contamination script in the Docker folder (GenomeQC/Docker/make_assemblyqc/). The contamination script in the Docker folder has been configured to use these two blobtool python scripts directly without the need to install BlobTools package or adding anything from that package. We are currently working on updating the github repo to make these things clear to the users. Thanks again for letting us know!
