### ISSUE TITLE
docker issue with tzdata

### ISSUE THREAD

**Issue by alxsimon** [HuffordLab/GenomeQC#3]
Hi, just to let you know that I had an issue with tzdata when compiling docker.
You need the following lines at the beginning of the dockerfile (just after apt update)

```
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow
RUN apt-get install -y tzdata
```
Additionnally, in the README of the Docker directory you are missing the end of the command to compile.
`docker build --no-cache -t assemblyqc make_assmeblyqc` otherwise docker complains.

This is on Ubuntu 18.04.

Cheers,
Alexis

**Comment by nm100** [comment]
Hi Alexis, 
Thank you for testing the GenomeQC docker on Ubuntu 18.04 system. I'll update the dockerfile for adding the time zone data. 
And -- yes you are right, I mistyped the end of the docker build command in the README file. I'll update this command too. Thanks again for pointing this out.
