### ISSUE TITLE
Update needed for the file GenomeQC/Docker/make_assemblyqc/Dockerfile 

### ISSUE THREAD

**Issue by qisun2** [HuffordLab/GenomeQC#4]
These three lines need to be changed in the Docker file. The link http://eddylab.org/software/hmmer/hmmer.tar.gz is an alias and it points to 3.3.1 now. "WORKDIR hmmer-3.3" would not work anymore. 

RUN wget http://eddylab.org/software/hmmer/hmmer.tar.gz
RUN tar zxf hmmer.tar.gz
WORKDIR hmmer-3.3

Change to:
RUN wget http://eddylab.org/software/hmmer/hmmer-3.3.1.tar.gz
RUN tar zxf hmmer-3.3.1.tar.gz
WORKDIR hmmer-3.3.1

**Comment by nm100** [comment]
Thanks for letting me know, @qisun2 
I'll update the docker file!
